/**
 * Humanitech Supply Trail
 *
 * Copyright (c) Humanitech, Peter Rogov and Contributors
 *
 * Website: https://humanitech.net
 * Repository: https://github.com/humanitech-net/supply-trail
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { Query, Resolver, Context } from '@nestjs/graphql';
import { Users } from './users.entity';
import { KeycloakService } from '../../auth/keycloak.service';
import { Request } from 'express'; // Import Request from express

@Resolver(() => Users)
export class UsersResolver {
  constructor(private readonly keycloakService: KeycloakService) {}

  @Query(() => Users)
  async getUser(@Context() context: { req: Request }) {
    const { req } = context;

    const token = req.headers['authorization'].split(' ')[1];
    const changepa = await this.keycloakService.changeUserPasswordByAdmin(
      'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMcEtwM1JpNVEtdXJLbEFzU2ZCaVpiaXV6Nk1qbFFkMDFOSmVwX1I0RXhBIn0.eyJleHAiOjE2OTc0NjY5ODUsImlhdCI6MTY5NzQ2NTE4NSwianRpIjoiMGZkNjVlYzctNjJlMC00MDE4LWEzZTAtODliMjA0Zjk5OTEyIiwiaXNzIjoiaHR0cHM6Ly9kZXYuc3VwcGx5LXRyYWlsLmh1bWFuaXRlY2gubmV0L2F1dGgvcmVhbG1zL2h1bWFuaXRlY2giLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiOGQzNDk1ZTAtNjEzZS00YWIxLWJlZmItNDQ3YzUwODExMGEwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibmVzdC1hcHBsaWNhdGlvbiIsInNlc3Npb25fc3RhdGUiOiI0NjhmYmFkYS00ZjZkLTQ0ODEtYjQyOC0wOTA0ZWZhODY0Y2YiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vZGV2LnN1cHBseS10cmFpbC5odW1hbml0ZWNoLm5ldC9hcGkvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtaHVtYW5pdGVjaCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjQ2OGZiYWRhLTRmNmQtNDQ4MS1iNDI4LTA5MDRlZmE4NjRjZiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImxldWxsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibGV1bDIiLCJnaXZlbl9uYW1lIjoibGV1bGwiLCJmYW1pbHlfbmFtZSI6IiIsImVtYWlsIjoibGV1bGxAZ21haWwuY29tIn0.Nup7PT-uxONUYb4CH-TLKTc9asyCD_e17xYmqxavmEs7nNi9E5JgGg3teZ8RVR_E-BWQcPzsB5B1SVn_2pYY9dxYiJbb2CZxnb4ziZIDOBMqjmvLN1FLax7zil2nskvod4jp9jKgdJacgu5Vabt81rDsOa01UqtB8NsU7p54M8Qhc_0MUqhmauZpBc6WyVq4l4cbyH-ZSVhDNTTKol6MjbIbsMj1sxtuNG_H9aajAYiguv2iz48DILLjEqHoCCjamVRFlXkQZovengfjzBVlExkbozu3EY2HFJh0j1mrYo5drCbNMm2eL48vCSFUzFTEq2aPg7w5wDDsd0FU1_Bsbw',
      'leul'
    );
    console.log(changepa);
    return this.keycloakService.getUser(
      'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMcEtwM1JpNVEtdXJLbEFzU2ZCaVpiaXV6Nk1qbFFkMDFOSmVwX1I0RXhBIn0.eyJleHAiOjE2OTc0NjY5ODUsImlhdCI6MTY5NzQ2NTE4NSwianRpIjoiMGZkNjVlYzctNjJlMC00MDE4LWEzZTAtODliMjA0Zjk5OTEyIiwiaXNzIjoiaHR0cHM6Ly9kZXYuc3VwcGx5LXRyYWlsLmh1bWFuaXRlY2gubmV0L2F1dGgvcmVhbG1zL2h1bWFuaXRlY2giLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiOGQzNDk1ZTAtNjEzZS00YWIxLWJlZmItNDQ3YzUwODExMGEwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibmVzdC1hcHBsaWNhdGlvbiIsInNlc3Npb25fc3RhdGUiOiI0NjhmYmFkYS00ZjZkLTQ0ODEtYjQyOC0wOTA0ZWZhODY0Y2YiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vZGV2LnN1cHBseS10cmFpbC5odW1hbml0ZWNoLm5ldC9hcGkvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtaHVtYW5pdGVjaCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjQ2OGZiYWRhLTRmNmQtNDQ4MS1iNDI4LTA5MDRlZmE4NjRjZiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImxldWxsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibGV1bDIiLCJnaXZlbl9uYW1lIjoibGV1bGwiLCJmYW1pbHlfbmFtZSI6IiIsImVtYWlsIjoibGV1bGxAZ21haWwuY29tIn0.Nup7PT-uxONUYb4CH-TLKTc9asyCD_e17xYmqxavmEs7nNi9E5JgGg3teZ8RVR_E-BWQcPzsB5B1SVn_2pYY9dxYiJbb2CZxnb4ziZIDOBMqjmvLN1FLax7zil2nskvod4jp9jKgdJacgu5Vabt81rDsOa01UqtB8NsU7p54M8Qhc_0MUqhmauZpBc6WyVq4l4cbyH-ZSVhDNTTKol6MjbIbsMj1sxtuNG_H9aajAYiguv2iz48DILLjEqHoCCjamVRFlXkQZovengfjzBVlExkbozu3EY2HFJh0j1mrYo5drCbNMm2eL48vCSFUzFTEq2aPg7w5wDDsd0FU1_Bsbw'
    );
  }
}
