name: Publish Docker Image to Docker Hub

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        working-directory: services/service-core # Set the working directory to the directory containing the Dockerfile
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/humanitech_service_docker

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/humanitech_service_docker
